class FailureException(AssertionError):
    ROBOT_CONTINUE_ON_FAILURE = True
    pass
